#page title
page_title                                : Kofezavr Scale App                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6702016819                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ru                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : # https://github.com/wdrs/FutulaCoffeeScale/releases                                          # Enter Google Play Store URL.
presskit_download_link                    : # https://coffeescaleapp.kofezavr.ru                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Kofezavr Scale                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Provides real-time control of coffee brewing parameters using Bluetooth scales.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Dmitry Berezkin                                
your_link                                 : https://kofezavr.ru                     
your_city                                 :                                 
email_address                             : info@kofezavr.ru
facebook_username                         : kofezavr                                          
instagram_username                        : kofezavr
twitter_username                          : kofezavr
github_username                           : 
youtube_username                          : Coffeesaurus
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Bluetooth Scales
    description                           : Works with Futula Kitchen Scale 3, LFScale CK811 or CK811BLE.
    fontawesome_icon_name                 : wifi

  - title                                 : Timer
    description                           : Provides timer (stopwatch) for your brewing.
    fontawesome_icon_name                 : stopwatch
    
  - title                                 : Weight
    description                           : Gets weight values in gramms from the scale via bluetooth up to 4 times per second.
    fontawesome_icon_name                 : dumbbell

  - title                                 : Flowrate
    description                           : Calculates flowrate (gramms per second) in real-time.
    fontawesome_icon_name                 : fill-drip

  - title                                 : Brew Ratio
    description                           : Gives you ability to save dose and calculates brew ratio (BR) in real-time during brewing.
    fontawesome_icon_name                 : percent

  - title                                 : Charts
    description                           : When you start the timer it draws total weight chart and flowrate chart.
    fontawesome_icon_name                 : chart-line
  
  - title                                 : Autostart
    description                           : Provides the ability to automatically start the timer with the first pour.
    fontawesome_icon_name                 : play

  - title                                 : Brewing Profiles
    description                           : Draws graphs of your brewing profiles for espresso, pour-overs and drip coffee.
    fontawesome_icon_name                 : clipboard

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
